<br /><br />
<div id="view-content">

<a href="<?php 
	echo $this->url(array('controller'=>'opportunities',
                              'action'=>'createpdf', 
                              'id'=>$this->entries['opportunity']['Id']));?>">Création du Pdf</a>

<table>
<thead>
<tr><td>Champ</td><td>Valeur</td></tr>
</thead>

<?php
foreach ($this->entries['opportunity'] as $cle=>$val) {
	echo '<tr><td>'.$cle.'</td><td>'.$val.'</td></tr>';
}

?>
</table>
</div>
<div id="view-content" class= "list">

<table> 
	<thead>
	<tr>
		<td>Action</td>
	<?php foreach ($this->entries['cols'] as $col) : 	?>
		<td><?php echo $col; ?></td>
	<?php endforeach; ?>
	</tr>
	</thead>
	
	<?php foreach ($this->entries['products'] as $element) : ?>
	<tr>
		<td><a href="<?php 
	echo $this->url(array('controller'=>'products',
                              'action'=>'edit', 
                              'id'=>$element['Product2Id']));?>">Détail</a>
                              
        </td>

		<?php foreach ($this->entries['cols'] as $col) : ?>
		<td><?php
		if (isset($element[$col])) {
			if (is_array($element[$col])) echo implode(',', $element[$col]);
			else echo $element[$col];
		}
		?></td>
				
		<?php endforeach;?>
	</tr>
	<?php endforeach;?>
</table>
</div>

<?php echo "rr";
 Zend_Debug::dump($this->entries['pdf']);?>